**1.Dataset that shows the number of bedrooms and the selling price for 20 houses in a particular neighborhood**

In [ ]:
import numpy as np
import random
import math
import scipy.stats as st
from scipy.stats import t
from sklearn.linear_model import LinearRegression

In [ ]:
Bedrooms = [1,1,1,2,2,2,2,3,3,3,3,3,3,3,4,4,4,5,5,6]
Prices = [120,133,139,185,148,160,192,205,244,213,236,280,275,273,312,311,304,415,396,488]

In [ ]:
x = np.array(Bedrooms)
y = np.array(Prices)

**2.	Using the Bedrooms data points:**

In [ ]:
#	Extract a random sample of size 10
sample_10 = np.random.choice(x,10)
sample_10

array([2, 3, 1, 3, 5, 3, 4, 3, 3, 4])

In [ ]:
#Compute the mean and standard deviation of the sample
sample_mean = sample_10.mean()
print("Mean :",sample_mean)
sample_sd = sample_10.std()
print("Standard Deviation:",sample_sd)

Mean : 3.1
Standard Deviation: 1.044030650891055


In [ ]:
#Compute the the mean of the population
pop_mean = x.mean()
print("Population Mean:",pop_mean)

Population Mean: 3.0


In [ ]:
#Computer the confidence interval of 95% using the sample 

LCL = sample_mean - 1.96 * (sample_sd / np.sqrt(len(sample_10)))
UCL = sample_mean + 1.96 * (sample_sd / np.sqrt(len(sample_10)))

# Print the confidence interval
print('The mean of the population with 95% confidence interval lies between [{:.2f}, {:.2f}]'.format(LCL, UCL))



The mean of the population with 95% confidence interval lies between [2.45, 3.75]


In [ ]:
# Check if the population mean lies between the upper and lower bounds of the interval
cf_mean_interval = (pop_mean >= LCL) and (pop_mean <= UCL)

# Print the result
if cf_mean_interval:
    print("The population mean is within the confidence interval.")
else:
    print("The population mean is outside the confidence interval.")


The population mean is within the confidence interval.


#3.	Using both of the Bedrooms and the Prices:

In [ ]:
#Compute the covariance and the correlation between the two variables
cov_mat = np.cov(x,y)
cov_mat



array([[1.89473684e+00, 1.33894737e+02],
       [1.33894737e+02, 1.00161553e+04]])

From the results we could say there exsists a postive relationship between the number of bedrooms and prices. So if the number of bedroom increases ,the prices also increases.

In [ ]:
corr_mat = np.corrcoef(x,y)
corr_mat


array([[1.        , 0.97193793],
       [0.97193793, 1.        ]])

Therefore, we can say that there is a strong positive correlation between number of bedrooms and the prices.

**Build a regression model and estimate the regression parameters (slope and intercept).**

In [ ]:
x=x.reshape((-1,1)) 
model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [ ]:
# finding the coefficient determination
r_sq =model.score(x,y)
print(f"coefficient of determination:{round(r_sq,4)}")

coefficient of determination:0.9447


In [ ]:
#Slope and Intercept
print(f"Intercept:{round(model.intercept_,4)}")
print(f"Slope:{round(model.coef_[0],4)}")

Intercept:39.45
Slope:70.6667


In [ ]:
#predict the model
y_hat = model.predict(x) 
print(f"predicted value :{y_hat}")

predicted value :[110.11666667 110.11666667 110.11666667 180.78333333 180.78333333
 180.78333333 180.78333333 251.45       251.45       251.45
 251.45       251.45       251.45       251.45       322.11666667
 322.11666667 322.11666667 392.78333333 392.78333333 463.45      ]


In [ ]:
#predict the model using intercept and slope (y=ax + b)
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted Value:\n{y_pred}")

predicted Value:
[[110.11666667]
 [110.11666667]
 [110.11666667]
 [180.78333333]
 [180.78333333]
 [180.78333333]
 [180.78333333]
 [251.45      ]
 [251.45      ]
 [251.45      ]
 [251.45      ]
 [251.45      ]
 [251.45      ]
 [251.45      ]
 [322.11666667]
 [322.11666667]
 [322.11666667]
 [392.78333333]
 [392.78333333]
 [463.45      ]]


In [ ]:
#Predict the house price for a house with 7 rooms
value =7
y_pred = model.intercept_ + model.coef_ * value
print("The predicted price with 7 rooms is : ", y_pred)

The predicted price with 7 rooms is :  [534.11666667]


In [ ]:
#Estimate the upper bound and the lower bounds of the prediction interval of a house with 7 rooms
alpha =0.1
N=20
df = N-2
re_error= np.sqrt(np.square(y-y_hat).sum()/(N-2))
s_error = re_error*((1+(1/N)+((np.square(value-x.mean()))/(np.square(x-x.mean()).sum()))))
#print(s_error)
t_value = t.ppf(1-alpha/2,df=df)
interval =t_value * s_error
y_pred = model.predict(np.array([[value]]))[0].round(4)
LP = round(y_pred - interval,4)
UP = round(y_pred + interval,4)

#print("Lower bound of prediction interval for a house with 7 rooms:", LP)
#print("Upper bound of prediction interval for a house with 7 rooms:", UP)
print(f"\tThe predicted price of 7 bedrooms  {y_pred} is within the interval  ({LP:.3f}, {UP:.3f})")









	The predicted price of 7 bedrooms  534.1167 is within the interval  (471.435, 596.799)


In [ ]:
# Using as sample of houses that have only 3 bedrooms 
bedrooms_3 = [price for i, price in enumerate(y) if x[i] == 3]
bedrooms_3



[205, 244, 213, 236, 280, 275, 273]

In [ ]:
samp_mean = np.mean(bedrooms_3)
samp_std = np.std(bedrooms_3)
print("Mean:",samp_mean)
print("Standard Deviation:",samp_std)

Mean: 246.57142857142858
Standard Deviation: 28.278498358076853


**5.	Try to find the lower price that can be payed for a house with 3 rooms using Tolerance interval**

In [ ]:
alpha =0.05
n = len(bedrooms_3)
df = n-1
# Tolerance interval value 
k2 = 2.447 

# Calculating the upper bound and lower bound
LB = samp_mean - k2 *(samp_std/np.sqrt(n))
UB = samp_mean + k2 *(samp_std/np.sqrt(n))

print(f"The lower price that can be paid for a house with 3 bedrooms is {LB:.2f}, which lies within the tolerance interval [{LB:.2f}, {UB:.2f}].")


The lower price that can be paid for a house with 3 bedrooms is 220.42, which lies within the tolerance interval [220.42, 272.73].


**6.	Try  to find the highest price that can be payed for a house with 3 rooms using Tolerance interval**

In [45]:
print(f"The highest price that can be paid for a house with 3 bedrooms is {UB:.2f}, which lies within the tolerance interval [{LB:.2f}, {UB:.2f}].")

The highest price that can be paid for a house with 3 bedrooms is 272.73, which lies within the tolerance interval [220.42, 272.73].
